### ISSUE TITLE
browserify-generated sourcemap contains output from JSX instead of input

### ISSUE THREAD

**Issue by skybrian** [andreypopp/reactify#19]
browserify has a debug option to generate a sourcemap. However, when used with reactify, the sourcemap contains the output from JSX, not the input. When you view a source file using Chrome's debugger,  the file will appear to contain the wrong content. This can be rather confusing since it looks like the original source file was overwritten.

It seems like reactify should work with browserify to merge the sourcemap from JSX with the sourcemap from browserify.

**Comment by andreypopp** [comment]
Source maps are in 1.0.

**Comment by naorye** [comment]
I am using 1.0 and I still have an issue. I created an issue here: https://github.com/substack/node-browserify/issues/1098
Is this the same problem? is it reactify's?
