### ISSUE TITLE
Reactify doesn't convert JSX to JS for modules in node_modules

### ISSUE THREAD

**Issue by DjebbZ** [andreypopp/reactify#20]
Hi,

I'm using reactify, and tried the following with versions 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0 and Browserify 3.31.2, 4.2.3, 5.13.1 and 6.2. Almost all combinations have been tested, but mostly reactify 0.14.0 with all aforementioned versions of Browserify.

The problem : I've developped a React component that is common to several sites, so I decided to share it by publishing it to our internal GitLab. The module ends up in `/node_modules`. Since then, either compilation fails because of a Parse Error, of it fails silently and the JSX of the component isn't transformed in the end. Before sharing it (and therefore putting the module into node_modules), the _exact_ same code was in my local hierarchy of folder and it worked perfectly fine.

**Steps to reproduce**

I've managed to create a minimal test case that exhibits the problem.

```
toto.js // Main file for my test
package.json // Contains alias to the browserify build command
node_modules/
--  toto/  // React component shared
------  index.js // Entry point
------  package.json // Contains the react dependency only
```

_toto.js_ :

``` javascript
var toto = require("toto");
```

_package.json_ :

``` json
"scripts": {
  "toto": "browserify -t reactify toto.js -o toto-out.js"
},
"dependencies": {
  "browserify": "6.2.0",
  "reactify": "https://github.com/andreypopp/reactify/archive/v0.14.0.tar.gz"
}
```

_node_modules/toto/index.js_ :

``` javascript
/** @jsx React.DOM */
"use strict";

var React = require("react");

var Toto = React.CreateClass({
    render: function() {
        return ( <h1>TOTO</h1> );
    }
});
```

_node_modules/toto/package.json_ :

``` json
{
  "name": "toto",
  "version": "0.0.0",
  "main": "index.js",
  "dependencies": {
    "envify": "~1.2.1",
    "react": "~0.9.0"
  }
}
```

**Case 1 : compilation fails**

The error happens with Browserify 3.31.2. When I type `npm run toto`, the following error happens :

``` shell
╰─$ npm run toto

> my-project@0.0.0 toto /SOME/PATH/
> browserify -t reactify toto.js -o toto-out.js

Error: Parsing file /SOME/PATH/node_modules/toto/index.js: Line 8: Unexpected token <

npm ERR! my-project@0.0.0 toto: `browserify -t reactify toto.js -o toto-out.js`
npm ERR! Exit status 1
...
```

The line 8 corresponds to the first occurence (and only here) of JSX in the React component (`<h1>TOTO</h1>`).

**Case 2 : compilation fails silenlty**

This happens with any version of Browserify >= 4, even the latest 6.2.0. `npm run toto` exits succesfully, but the JSX isn't compiled at all so the code fails in the browser with a syntax error. In _toto-out.js_ I can see it : 

``` javascript
},{}],2:[function(require,module,exports){
/** @jsx React.DOM */
"use strict";

var React = require("react");

var Toto = React.CreateClass({
    render: function() {
        return ( <h1>TOTO</h1> );
    }
});

},{"react":132}],3:[function(require,module,exports){
```

*\* Hints **

The error message comes from module-deps. It's supposed to execute any transform before parsing the file, as explained [here](https://github.com/substack/module-deps#transforms). In case 1, it's like the transform isn't executed at all or registered to execute after parsing, hence the error. In case 2, it's like it's executed but not written to disk, not sure exactly. I tried debugging but I don't have time to dive into the Browserify stack in details, and I'm not sure where to start. My temporary workaround will be to transform the JSX upfront so that I `require` a normal JS file.

I hope the report was detailed enough so you can have a look. I'm not even sure it's related to reactify or module-deps. If I'm wrong I'd be happy to recreate the issue in the appropriate location.

**Comment by graue** [comment]
@andreypopp What's the thinking behind this design? It seems strange that I should have to maintain a fork of a dependency (in my case [react-menu](https://github.com/instructure-react/react-menu)) with local edits to its package.json file just to get it to play nice with Reactify. This introduces the need to check the dependency into my source control and manually merge in changes when updating it.

**Comment by andreypopp** [comment]
@graue this is the design decision made by Browserify. You should try to get your fixes to react-menu merged back to upstream or use reactify with `global: true` as indicated in the discussion above.

**Comment by graue** [comment]
Thank you, Andrey. I was thinking in a perfect world, react-menu wouldn't have to cater to Browserify (maybe they build their own apps using Webpack or something else). But that may be too idealistic of me. I sent them a PR instead, as you suggested.
