### ISSUE TITLE
Unexpected token < while parsing file

### ISSUE THREAD

**Issue by jkehler** [andreypopp/reactify#26]
I can't get reactify to work. No matter what I do I keep getting this Parse Error.

```
ReactifyError: /path/to/my/file: Parse Error: Line 6: Unexpected token < while parsing file: /path/to/my/file
```

My file itself contains basically nothing for testing purposes.

```
var React = require('react');

var App = React.createClass({
  render: function() {
    return {
      <div>
        <p>testing</p>
      </div>
    };
  }
});
```

What am I doing wrong?

**Comment by zhangda89** [comment]
no
<p className=''><span className='badge'>ST</span>->{startime}</p>
this is code ?
Error: Parse Error: Line 151: Unexpected token >
because i add this "->"
