### ISSUE TITLE
 Unexpected token on symlinks

### ISSUE THREAD

**Issue by rkmax** [andreypopp/reactify#38]
I have my src directory symlink to node_modules
```
$ cd node_modules; ln -s ../src app
```

when i dont know if i require a component like this
```js
var Input = require('app/component/input');
```

I get the `Parsin file /home/rkmax/project/node_modules/app/component/input.js` Unexpected token` 

if i use the relative path works fine :(

**Comment by theponti** [comment]
@rkmax @jacklenox +1 I'm having the same issue using symlinks. Has anyone found a solution to this issue?

**Comment by andreypopp** [comment]
Again, I think it's worth filing an issue to browserify, because reactify alone doesn't resolve any modules and only applies tranform for `.js` or `.jsx` files.

**Comment by tkurki** [comment]
Bumped against this one as well.

Some explanation available at substack/node-browserify#993

**Comment by tkurki** [comment]
tkurki/browserify-reactify-symlink-test@c3a3223739a6321b84e4fe397bb537f101bc859b fixed the issue for my toy test project.

**Comment by theponti** [comment]
@tkurki :+1: Definitely going to give this a try.

**Comment by andreypopp** [comment]
Closing as this is not a reactify issue.
