### ISSUE TITLE
Configuring ES6 in task? 

### ISSUE THREAD

**Issue by ezmiller** [andreypopp/reactify#53]
I have a browserify task that is configured like so:

```
module.exports = function(grunt) {

  grunt.config.set('browserify', {
    dev: {
      src: 'assets/js/main.jsx',
      dest: '.tmp/public/js/main.js',
      options: {
        debug: true,
        extensions: ['.jsx'],
        transform: ['reactify']
      }
    }
  });

  grunt.loadNpmTasks('grunt-browserify');
};
```

I tried configuring it to use es6 this way:
```
module.exports = function(grunt) {

  grunt.config.set('browserify', {
    dev: {
      src: 'assets/js/main.jsx',
      dest: '.tmp/public/js/main.js',
      options: {
        debug: true,
        extensions: ['.jsx'],
        transform: ['reactify', {'es6': true}]
      }
    }
  });

  grunt.loadNpmTasks('grunt-browserify');
};
```

This causes an error though:

>  Error: path must be a string

I can't understand from the docs how to do this given that I don't want to configure the transform in my package.json.  Any help would be appreciated.

**Comment by davidreher** [comment]
Same for me. I already tried to copy reactify-master over my npm package but this does'nt solve the issue.

**Comment by ezmiller** [comment]
@davidreher the way I ended up fixing this was by adding a second set of brackets so that transform is an array of transforms. I had this wrong in the code above: see the answer [on stackoverflow](http://stackoverflow.com/questions/28719550/getting-reactify-and-browserify-to-work-with-es6).
