### ISSUE TITLE
Surface nonStrictEs6module option

### ISSUE THREAD

**Issue by danvk** [andreypopp/reactify#58]
[`non-strict-es6-module`][1] is a new option to `jsx` and react-tools `transform` which must be set to enable [type imports][2] in Flow. It should be possible to set this in reactify.

Or, let the user specify options to pass directly to `transform` so that this is never an issue again?

[1]: https://github.com/facebook/react/blob/b0a59a643a4e88832cbedf7a9b816fdc2839b9cd/bin/jsx#L29
[2]: http://flowtype.org/blog/2015/02/18/Import-Types.html

**Comment by TimeBomb** [comment]
The original pull request for this `nonStrictEs6Module` flag and the `es6module` flag can be found at https://github.com/facebook/react/pull/3143, which includes specific information about them. Unfortunately not officially documented yet, so it appears.

**Comment by ezmiller** [comment]
How does one set these flags in a Grunt configuration when using browserify and reactify as a transform? I created a [stackoverflow question](http://stackoverflow.com/questions/29591818/how-to-transpile-react-es6-classes-using-grunt-browserify-reactify) about this.

**Comment by danvk** [comment]
Here's my fix: https://github.com/andreypopp/reactify/pull/59

**Comment by MatthewHerbst** [comment]
Any updates here? I'm running into this problem (as seen in #60 ) also.

**Comment by danvk** [comment]
Can you use jstransformify instead of reactify? I recently made [some changes][1] to make its interface more like reactify.

[1]: https://github.com/andreypopp/jstransformify/pull/6

**Comment by MatthewHerbst** [comment]
@danvk When I switched my transform from

`bundler.transform(reactify, {es6:true});`

to

`bundle.transform(jstransformify);`

I get the error:

```
Error: while transforming /Users/mherbst/Repos/data-validation-tool/src/client/js/app.jsx:Error: Parse Error: Line 1: Illegal import declaration
```

**Comment by MatthewHerbst** [comment]
I was able to use `babelify` instead of `reactify` and it solved all my problems.

**Comment by andreypopp** [comment]
Yeah, `reactify` is pretty much deprecated now as `babel` is replacing `jstransform`.

**Comment by DannyvanderJagt** [comment]
@MatthewHerbst Thank you that worked for me too!

**Comment by alex179ohm** [comment]
@MatthewHerbst Tanks! babelify works fine for me too
