### ISSUE TITLE
Use jstransform directly instead of react-tools

### ISSUE THREAD

**Issue by zpao** [andreypopp/reactify#65]
I'm going to kill off react-tools. We haven't made a lot of noise about it but I will soon. I already shipped an updated version of jstranform with an API that is very similar to react-tools so the switch should be pretty easy. [I even wrote a migration guide.](https://github.com/facebook/jstransform#migration-guide) This let's us ship transforms faster and not block on React releases.

It would be great if reactify could upgrade :)

**Comment by jjmasse** [comment]
@zpao is migrating to jsTransform still valid?  This [deprecation report](https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html) says otherwise.

Or, will jsTransform it continue to be maintained as its own library?

**Comment by zpao** [comment]
It's more valid than depending on react-tools but we're not planning on supporting jstransform anymore either.

**Comment by jjmasse** [comment]
@zpao Thats fair - thank you for clarifying.
