### ISSUE TITLE
Source maps include full local path names, not shown in original folders

### ISSUE THREAD

**Issue by davepile** [andreypopp/reactify#68]
When I bundle with this command - `watchify main.js -t reactify -o bundle.js -v -d` the source file names appear in devtools with the file name including the full local file path and they are not shown in their nested folders.

This causes a few problems with many files as it is hard to see which file you are looking at.

I have posted a [SO question](http://stackoverflow.com/questions/30227862/browserify-and-reactify-source-maps-include-full-local-path-names) which includes some screenshots that might help explain what I mean. 

Is there a solution to this or am I doing something wrong?
Thanks
(If cross posting or linking etc. is frowned upon let me know and I will remedy- i am new to issues on github)

**Comment by davepile** [comment]
I had someone answer this on the  [SO question](http://stackoverflow.com/questions/30227862/browserify-and-reactify-source-maps-include-full-local-path-names/30238645#30238645).

It was a browserify option that fixed the issue- adding `--full-paths=false` to the comman worked. This is the final command that worked for me.

`watchify main.js -t reactify -o bundle.js -v -d --full-paths=false`

**Comment by zertosh** [comment]
@davepile You're probably using an old version of watchify. Prior to 2.5.0, `fullPaths` was required for the caching to work, thus the CLI automatically added it. If you update to a newer version, you won't have to set `--full-paths` to false, since that's already the default.

**Comment by davepile** [comment]
@zertosh - I have watchify 2.5.1 installed globally and in the project
