### ISSUE TITLE
switch to babel instead of react-tools

### ISSUE THREAD

**Issue by acornejo** [andreypopp/reactify#73]
the react team has announced that react-tools and jstransformer will be deprecated.

will reactify be migrated to use babel anytime soon?

announcement here:

http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by andreypopp** [comment]
No reason to do that, there's [babelify](https://github.com/babel/babelify).

**Comment by wjordan** [comment]
@andreypopp does this answer mean that `reactify` [should be deprecated in favor of babelify](https://github.com/andreypopp/reactify/issues/75) for React >= 0.14 to eliminate confusion?

**Comment by andreypopp** [comment]
Yes
